name: Build OBJ file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: karcherm/action-install-jw@v0.0.2
        with:
          jwasm: true
      - name: Assemble the patch
        run: jwasm -Fosdms_8g.obj sdms_8g.asm
      - uses: actions/upload-artifact@v2
        with:
          name: sdms_8g
          path: |
            sdms_8g.obj
            pcii0306.map
            si4i0306.map
